### ISSUE TITLE
40 column video memory mirroring not working

### ISSUE THREAD

**Issue by rhester72** [MiSTer-devel/PET2001_MiSTer#11]
Please observe the following VICE behavior when directly manipulating screen memory.

In 40 column mode, the start of screen memory (at $8000) is mirrored into the 80 column region, such that POKEing a memory location changes the same location in the 80 column half of RAM:

![vice40](https://github.com/MiSTer-devel/PET2001_MiSTer/assets/7516483/8bd27316-50e5-4f9e-bcef-25192127e7c8)

which obviously doesn't (and can't) occur in 80 column mode:

![vice80](https://github.com/MiSTer-devel/PET2001_MiSTer/assets/7516483/1bd2dca6-48d8-4431-be2c-7232d9b545f2)

This mirroring does not happen currently in the core, which breaks 80-column detection routines like those used in later issues of CURSOR magazine.

Proper mirroring would be:

$8000-83FF -> $8400-87FF (per testing with the 4032 in VICE 3.7)

**Comment by rhester72** [comment]
Confirmed as fixed, thanks very much!

**Comment by rhester72** [comment]
Sincere apologies - now that I know the real-world target is a 2001-32N, a bit more mirroring is needed if historical accuracy is desired.

$8000-83FF (on the 2001 only!) mirrors to _three_ ranges:

$8400-87FF
$8800-8BFF
$8C00-8FFF

**Comment by sorgelig** [comment]
I'm not familiar with PET, but according to VICE we can emulate also 3008,3016,3032 models without much changes. Are those mirroring are really required to make some software working? Since we have custom ROM loading now, we can use 8800-8FFF for some ROM versions.

**Comment by Rhialto** [comment]
The 30xx models only mirror $8000-83FF to $8400-87FF, but the 2001 also mirrors it to the other 2 mentioned ranges.
30xx is the European name, it may be (but I'm not 100% certain) that the American 2001-32N is the same in this detail.
Also, people might have upgraded their original 2001 with newer ROMs, so in practice many combinations existed.

**Comment by rhester72** [comment]
@Rhialto Agreed, but I believe the intent isn't necessarily to be 100% faithful to the 32N as much as "in the spirit of it".  That being the case, at least for the software I've tested, mirroring to only $8400 appears to be sufficient for available real-world software (if you're aware of other 2001 software leveraging or even assuming the other mirrors are present, I'd be happy to know!).

**Comment by Rhialto** [comment]
I do recall some software that (probably unintentionally) made use of the extra mirrored addresses. I think it was called BASICLES. It has been a while, but there would be only some things missing from the screen when the mirrors are not all implemented, so you'd not even be sure if the program was really broken. Ah, I found it on [zimmers.net](https://www.zimmers.net/anonftp/pub/cbm/pet/programming/lessons/index.html). You see it on page 5, "here they are:" and then a lot of nothing.

Anyway, in the [fork](https://github.com/Rhialto/PET2001_MiSTer/) I made to port the PET to the Mega-65 I am making this sort of thing exact. I also have exact video timing so that racing-the-beam programs work. For example, `HI-RES` from [cursor 18](https://www.zimmers.net/anonftp/pub/cbm/magazines/cursor/index.html). From the recent years there are more demos that depend on this. They work in VICE, they should work on an FPGA version. (I am the PET maintainer of VICE so I have to keep up my reputation a bit...)

**Comment by rhester72** [comment]
@Rhialto Greetings!  VICE PET is truly a thing of beauty and a labor of love - I use it extensively on Retroarch (I know, boo hiss, but #shaders lol).  I've seen your incremental improvements over recent years, and they were/are most welcome!

Sure, I'd love if we had that sort of accuracy, but I think the sheer number of configuration variations makes it hella impractical.  I'm perfectly fine with the core representing the 'spirit' of the PET if not an exacting implementation, as it's reasonable to have something that runs 99% of the software as you'd expect.  Like the beam-racers...they are CRTC, but (for my dollar) the original 8N video is superior (at least in terms of appearance on actual hardware).

Still, I'm sure any enhancements you've made for the Mega-65 would be most welcome backports...sadly, I lack that skill, and despite Sorg's continued urging I'm too old and busy to learn.  *laughs*

Well met!  You're kind of a hero in my book.  =)
